	Samira Hachimi <samira.hachimi@oracle.com>,
Larisa Dobrescu <larisa.dobrescu@oracle.com>,
Jeanine Chivu <jeanine.chivu@oracle.com>,
Fatima Zahra MOUAK <fatima.mouak@oracle.com>,
Imane Beni-Aich <imane.beni-aich@oracle.com>,
Jihane IDRISSI JANATI <jihane.idrissi.janati@oracle.com>,
"achrafmaghous@gmail.com" <achrafmaghous@gmail.com>,
"fatimazahradrissi01@gmail.com" <fatimazahradrissi01@gmail.com>,
"najiilyassoo@gmail.com" <najiilyassoo@gmail.com>,
"kenza.boumraime@gmail.com" <kenza.boumraime@gmail.com>,
"maryembenhadin@gmail.com" <maryembenhadin@gmail.com>,
"youssefbouhaous01@gmail.com" <youssefbouhaous01@gmail.com>,
"faouzi.elhazzat@gmail.com" <faouzi.elhazzat@gmail.com>,
"soukaina.jabri333@gmail.com" <soukaina.jabri333@gmail.com>,
"linab6ab@gmail.com" <linab6ab@gmail.com>,
"naamaabderrahmane2002@gmail.com" <naamaabderrahmane2002@gmail.com>,
"alabadila.malai1@gmail.com" <alabadila.malai1@gmail.com>,
"mezianeamine1024@gmail.com" <mezianeamine1024@gmail.com>,
"anas.aberchih1@gmail.com" <anas.aberchih1@gmail.com>,
"jawad.arbahi12@gmail.com" <jawad.arbahi12@gmail.com>,
"elghayate28@gmail.com" <elghayate28@gmail.com>,
"boudrimeryem11@gmail.com" <boudrimeryem11@gmail.com>,
"aoukacha.moussa@gmail.com" <aoukacha.moussa@gmail.com>,
"naoufaljrh2000@gmail.com" <naoufaljrh2000@gmail.com>,
"akramfullstudy01@gmail.com" <akramfullstudy01@gmail.com>,
"oumyassire555@gmail.com" <oumyassire555@gmail.com>,
"bahessourihab1@gmail.com" <bahessourihab1@gmail.com>,
"moustadrifayman@outlook.com" <moustadrifayman@outlook.com>,
"yaimane2018@gmail.com" <yaimane2018@gmail.com>,
"a.drissiachir@gmail.com" <a.drissiachir@gmail.com>,
"boupouchi.anass@gmail.com" <boupouchi.anass@gmail.com>,
"ibtissammassa16@gmail.com" <ibtissammassa16@gmail.com>,
"boulamtatimane@gmail.com" <boulamtatimane@gmail.com>,
"rachidatanassat123@gmail.com" <rachidatanassat123@gmail.com>,
"eljakaniyassin@gmail.com" <eljakaniyassin@gmail.com>,
"achrafzhar2@gmail.com" <achrafzhar2@gmail.com>,
"raghiahaidari02@gmail.com" <raghiahaidari02@gmail.com>,
"kawtar20.bensalim@gmail.com" <kawtar20.bensalim@gmail.com>,
"adam.houlihal@usmba.ac.ma" <adam.houlihal@usmba.ac.ma>,
"aitounaayoubb@gmail.com" <aitounaayoubb@gmail.com>,
"chakhisamjed@gmail.com" <chakhisamjed@gmail.com>,
"az.ayoubsarab2002@gmail.com" <az.ayoubsarab2002@gmail.com>,
"lahoucine.digrari@edu.uiz.ac.ma" <lahoucine.digrari@edu.uiz.ac.ma>,
"maarosaid8@gmail.com" <maarosaid8@gmail.com>,
"elqajjam@gmail.com" <elqajjam@gmail.com>,
"elhaddaditarek@gmail.com" <elhaddaditarek@gmail.com>,
"yassine.elbadraoui@gmail.com" <yassine.elbadraoui@gmail.com>,
"zelharchi40@gmail.com" <zelharchi40@gmail.com>,
"sajidabderrahmane59@gmail.com" <sajidabderrahmane59@gmail.com>,
"alyae.essiba0@gmail.com" <alyae.essiba0@gmail.com>,
"ismail.disatra@gmail.com" <ismail.disatra@gmail.com>,
"salmiyassir01@gmail.com" <salmiyassir01@gmail.com>,
Soukaina Inan <soukaina.inan@oracle.com>